In [1]:
#üçgen matris

In [45]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [9]:
M = np.random.randn(5,5)
print(M)
print("\n")
      
U = np.triu(M)
print("Upper triangular matrix - \n", U)
print("\n")
L = np.tril(M)
print("Lower triangular matrix - \n", L)

[[ 0.43289501 -1.08578766 -1.6190661   0.01498718 -0.70580075]
 [ 0.01368025  1.420475    0.12282544  0.79241785 -1.62566695]
 [ 0.75542637  1.23967446  0.57545525  1.87429    -0.40514205]
 [-1.65955717  0.34389227  0.90054082  1.35184587  1.80449364]
 [ 2.40805849 -0.17307887  1.0768061   1.17064431  0.52598084]]


Upper triangular matrix - 
 [[ 0.43289501 -1.08578766 -1.6190661   0.01498718 -0.70580075]
 [ 0.          1.420475    0.12282544  0.79241785 -1.62566695]
 [ 0.          0.          0.57545525  1.87429    -0.40514205]
 [ 0.          0.          0.          1.35184587  1.80449364]
 [ 0.          0.          0.          0.          0.52598084]]


Lower triangular matrix - 
 [[ 0.43289501  0.          0.          0.          0.        ]
 [ 0.01368025  1.420475    0.          0.          0.        ]
 [ 0.75542637  1.23967446  0.57545525  0.          0.        ]
 [-1.65955717  0.34389227  0.90054082  1.35184587  0.        ]
 [ 2.40805849 -0.17307887  1.0768061   1.17064431  0.525

In [10]:
# SWAP satır/sutün

In [11]:
m1 = np.arange(0,16).reshape(4,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
m1[[3,2]] = m1[[2,3]]
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [15]:
m2 = np.arange(0,36).reshape(6,6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
m2[:, [2,3]] = m2[:, [3,2]]
m2

array([[ 0,  1,  3,  2,  4,  5],
       [ 6,  7,  9,  8, 10, 11],
       [12, 13, 15, 14, 16, 17],
       [18, 19, 21, 20, 22, 23],
       [24, 25, 27, 26, 28, 29],
       [30, 31, 33, 32, 34, 35]])

In [19]:
#Transpose

In [30]:
M = np.array([[1,2,3,0,81],[5,6,7,22,42],[10,11,1,13,84],[17,41,3,17,66],[77,47,37,97,61]])
M

print(np.transpose(M))

#veya

print(M.T)

[[ 1  5 10 17 77]
 [ 2  6 11 41 47]
 [ 3  7  1  3 37]
 [ 0 22 13 17 97]
 [81 42 84 66 61]]
[[ 1  5 10 17 77]
 [ 2  6 11 41 47]
 [ 3  7  1  3 37]
 [ 0 22 13 17 97]
 [81 42 84 66 61]]


In [31]:
print(np.linalg.det(M))

-17808752.00000002


In [32]:
print(np.linalg.matrix_rank(M))

5


In [33]:
M1 = np.array([[1,2],[4,5]])
M1

array([[1, 2],
       [4, 5]])

In [34]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [35]:
np.linalg.matrix_power(M1,3)

array([[ 57,  78],
       [156, 213]])

In [36]:
#Tensörler

In [37]:
T1 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,20,30],[40,50,60],[70,80,90]],
    [[100,200,300],[400,500,600],[700,800,900]],
])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [38]:
T2 = np.array([
    [[0,0,0],[0,0,0],[0,0,0]],
    [[1,1,1],[1,1,1],[1,1,1]],
    [[2,2,2],[2,2,2],[2,2,2]],
])
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [39]:
A = T1 + T2
A #veya 
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [40]:
S = T1 - T2
S #veya 
np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [41]:
P = T1 * T2
P #veya 
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [46]:
D = T1 / T2
D #veya 
np.divide(T1, T2)

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])