In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [5]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [6]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [7]:
ar1 = np.arange(1,20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
ar1 = np.arange(1,20)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [21]:
np.random.random(5) #defoult 0-1 aralığında üretir

array([0.39211752, 0.34317802, 0.72904971, 0.43857224, 0.0596779 ])

In [22]:
np.random.randint(0,500,5)

array([ 96, 208,  68, 305, 311])

In [23]:
np.random.seed(123) #çekirdek değeri kullanarak sabitleme
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [20]:
np.random.seed(123) #çekirdek değeri kullanarak sabitleme
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [18]:
np.random.seed(121) #çekirdek değeri kullanarak sabitleme
np.random.randint(0,100,10)

array([66, 85,  8, 95, 65, 52, 83, 96, 46, 34])

In [27]:
f1 = np.random.uniform(5,10, size =(10))
f1

array([6.96058759, 6.71589008, 8.64524854, 7.19286122, 5.29838948,
       6.99022128, 8.68997703, 5.91245865, 5.87725878, 7.65775687])

In [28]:
np.floor(f1)
np.trunc(f1)


array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [29]:
np.trunc(f1)

array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [30]:
f1.astype(int)

array([6, 6, 8, 7, 5, 6, 8, 5, 5, 7])

In [32]:
b2 = np.random.randn(10) #mean = 0 variance = 1
b2

array([ 2.20742744,  0.52274247,  0.46564476,  0.72491523,  1.49582653,
        0.74658059, -1.10098526, -1.4103012 , -0.74765132, -0.98486761])

In [33]:
arr1 = np.array([10,20,30,40,50,60])
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [34]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [35]:
arr2.sum()

190

In [36]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [39]:
#np.min(arr2) np.max(arr2) np.mean(arr2) 

10.0

In [40]:
np.std(arr2)

5.477225575051661

In [53]:
A = np.array([[1,2,3,0,81],[5,6,7,22,42],[10,11,1,13,84],[17,41,3,17,66],[77,47,37,97,61]])
A

array([[ 1,  2,  3,  0, 81],
       [ 5,  6,  7, 22, 42],
       [10, 11,  1, 13, 84],
       [17, 41,  3, 17, 66],
       [77, 47, 37, 97, 61]])

In [54]:
A.sum()

751

In [55]:
A.max()

97

In [56]:
np.amin(A, axis = 0) #np da axis = 0 sütuna karşılık gelir axis = 1 satıra denk gelir

array([ 1,  2,  1,  0, 42])

In [57]:
A.mean() #median() , var(), std()

30.04

In [58]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(0, 4) 81
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(1, 4) 42
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(2, 4) 84
(3, 0) 17
(3, 1) 41
(3, 2) 3
(3, 3) 17
(3, 4) 66
(4, 0) 77
(4, 1) 47
(4, 2) 37
(4, 3) 97
(4, 4) 61


In [60]:
a = np.array([7,8,5,6,4])
a

array([7, 8, 5, 6, 4])

In [61]:
a[0]

7

In [62]:
a[1:3]

array([8, 5])

In [63]:
a[-1]

4

In [64]:
#elemanları dizi işerisinde değiştirme

In [75]:
ar =np.arange(0,20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [77]:
rep1 = np.where(ar % 2 == 0, 0, ar)
rep1

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [79]:
ar2 = np.array([10,20,30,10,10,20,20,])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [81]:
rep2 = np.where(ar2 == 10, 99, ar2)
rep2

array([99, 20, 30, 99, 99, 20, 20])

In [82]:
p2 = np.arange(0,100,10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
np.put(p2,[0,3,5],[11,22,33])
p2

array([11, 10, 20, 22, 40, 33, 60, 70, 80, 90])