In [1]:
#Numpy

In [3]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [4]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [5]:
type(list1)

list

In [6]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.data

In [9]:
arr1.dtype

dtype('int32')

In [11]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [16]:
arr3 = np.arange(0,10)
arr3.shape

(10,)

In [21]:
arr3.size #veya
len(arr3)

10

In [19]:
arr3.nbytes #4 bytes yer kaplar 10*4

40