In [1]:
"""
scipy.linalg, scipy.special, scipy.integrate, scipy.optimize, 
scipy.fftpack, scipy.signal, scipy.stats, scipy.ndimage, scipy.io

"""

'\nscipy.linalg, scipy.special, scipy.integrate, scipy.optimize, \nscipy.fftpack, scipy.signal, scipy.stats, scipy.ndimage, scipy.io\n\n'

In [2]:
import numpy as np
from scipy import linalg

In [5]:
A = np.array([[1,2], [3,4]])
print(A)

B= linalg.inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
b = np.array([[5,6], [7,8], [9,10]])
print (b.T)

[[ 5  7  9]
 [ 6  8 10]]


In [8]:
#Denklem takımlarının çözümü
A = np.array([[1,3,5], [2,5,1],[2,3,8]])
b = np.array([[10], [8], [3]])

print(linalg.inv(A).dot(b))
print(np.linalg.solve(A,b))
              

              

[[-9.28]
 [ 5.16]
 [ 0.76]]
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [9]:
A.T

array([[1, 2, 2],
       [3, 5, 3],
       [5, 1, 8]])

In [10]:
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [11]:
A.size

9

In [12]:
#İntegral

In [15]:
from scipy import integrate
x2 = lambda x : x**2
I = integrate.quad(x2,  0, 6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [16]:
#türev

In [18]:
from scipy.misc import derivative
def f(x):
    return x**3 + x**2
D = derivative(f, 1.0, dx = 1e-6)
print(D)

4.999999999921734
